-- Grant Openflow access to test_tenant database
-- Run with: snowsql -f grant_openflow_access.sql

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SMDH_WH;

-- Grant database usage
GRANT USAGE ON DATABASE SMDH_TENANT_TEST_TENANT TO ROLE OPENFLOW_RUNTIME_ROLE_KINESIS;

-- Grant schema usage on RAW
GRANT USAGE ON SCHEMA SMDH_TENANT_TEST_TENANT.RAW TO ROLE OPENFLOW_RUNTIME_ROLE_KINESIS;

-- Grant CREATE TABLE (so Openflow can auto-create the destination table)
GRANT CREATE TABLE ON SCHEMA SMDH_TENANT_TEST_TENANT.RAW TO ROLE OPENFLOW_RUNTIME_ROLE_KINESIS;

-- Grant INSERT and SELECT on all existing and future tables
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA SMDH_TENANT_TEST_TENANT.RAW TO ROLE OPENFLOW_RUNTIME_ROLE_KINESIS;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA SMDH_TENANT_TEST_TENANT.RAW TO ROLE OPENFLOW_RUNTIME_ROLE_KINESIS;

-- Verify grants
SHOW GRANTS TO ROLE OPENFLOW_RUNTIME_ROLE_KINESIS;

SELECT 'Grants completed for OPENFLOW_RUNTIME_ROLE_KINESIS on SMDH_TENANT_TEST_TENANT' AS status;
